config/routes.rb
Rails.application.routes.draw do

  root 'index#home'

  resources :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: 25 %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1> </h1>

<%= render 'form' %>

<%= link_to 'Show', @idea, :class=>"btn btn-default" %> |
<%= link_to 'Back', ideas_path, :class=>"btn btn-default" %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Developers storytelling</h1>
<hr/>
  <% @ideas.each do |idea| %>
    <article>
      <%= link_to idea.name, idea, { :class=>"h2" } %>
      
      <section><%= idea.description %></section>

      <div class="text-right">

      <div class="btn btn-default">
        <%= link_to 'Edit', edit_idea_path(idea), {  :class=>"fa fa-pencil-square-o fa-lg" } %>
      </div>

      <div class="btn btn-default">
        <%= link_to 'Delete', idea, :class=>"fa fa-trash-o fa-lg",method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      
      </div>
    </article>
    <hr/>

  <% end %>


<br>

<%= link_to 'Add article', new_idea_path, { :class=>"btn btn-default" } %>

app/views/ideas/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path, :class=>"btn btn-default" %>
<%= link_to 'Edit', ideas_path, :class=>"btn btn-default" %>

app/views/ideas/show.html.erb
<div class="viewcontainer">

<p id="notice"><%= notice %></p>

<p>
  <strong><%= @idea.name %></strong>
</p>
<p>
  <%= @idea.description.html_safe %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea), :class=>"btn btn-default" %> 
<%= link_to 'Back', ideas_path, :class=>"btn btn-default"  %>
</div>

app/views/index/home.html.erb
<h1>Developers storytelling</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpmeout</title>
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main-container" class="container">
      
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
</body>
</html>